apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcluster-gateway-sa
  namespace: gcp
  annotations:
    meta.helm.sh/release-name: vcluster-gateway
    meta.helm.sh/release-namespace: gcp
  labels:
    app: vcluster-gateway
    app.kubernetes.io/managed-by: Helm
