apiVersion: v1
entries:
  vcluster-k8s:
  - apiVersion: v2
    appVersion: 0.18.1
    created: "2024-12-20T17:52:38.489254+08:00"
    description: vcluster - Virtual Kubernetes Clusters (k8s)
    digest: e3dcb8b2cd58362816e0de0eb88afef88b031a8219f3dd041bc05296994c3526
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster-k8s
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-k8s-0.18.1.tgz
    version: 0.18.1
generated: "2024-12-20T17:52:38.488276+08:00"
