#
# Copyright 2023 The Zetyun.GCP Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  platform: gcp
  serverName: app-gateway
  region: cn-maanshan-a
  tokenKey: X-Access-Token
  respCacheKey: respBody
  port: 8080
  swagger:
    host: "op.gcp-dev.zetyun.cn"
    basePath: "/api/"

mysql:
  pool_max: 2
  # url: 'appgateway:Zetyun2024@tcp(10.220.9.62:31306)/appgateway?charset=utf8mb4&parseTime=True&loc=Local'
  url: 'appgateway:DataCanvas!23@tcp(10.220.9.91:33310)/appgateway?charset=utf8mb4&parseTime=True&loc=Local'

casdoor:
  endpoint: https://sso.ops01.zetyun.cn/

iam:
  policyEndPoint: http://iam:8889/gcp/iam/v1/user/listpolicies

cache:
  enable: true
  lifeTime: 30
  cleanWindow: 60
  hardMaxCacheSize: 1024
  shards: 128

aps:
  apikey: "9E6E6F0469841CAED056B194B0CF3FB4"
  
alayaStudio:
  apiKey: "IgkPKRZqJOFnHl65B2jisYAUXaz9oG3V"

metrics:
  endpoint: http://resource-metric-svc.aps-os.svc.cluster.local:9090

iamagent:
  # endpoint: http://catalog-proxy.aps-os.svc.cluster.local:8080
  endpoint: http://10.220.11.133:31462