// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type Request struct {
	Name        string `path:"name,options=[you,me]"` // parameters are auto validated
	CreateTimes string `path:"time,options=[you,me]"`
}

type Response struct {
	Message string `json:"message"`
}
