// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AddUserRequest struct {
	Authorization string `header:"authorization"`
	Name          string `json:"name"`
	Age           string `json:"age"`
}

type AddUserResponse struct {
	Message string `json:"message"`
}

type DeleteUserRequest struct {
	Authorization string `header:"authorization"`
	Name          string `path:"name"`
}

type DeleteUserResponse struct {
	Message string `json:"message"`
}

type GetUserRequest struct {
	Authorization string `header:"authorization"`
	Name          string `path:"name"`
	Delete        bool   `form:"delete,optional"`
}

type GetUserResponse struct {
	CreateTime string `json:"create_time"`
	Name       string `json:"name"`
	Age        string `json:"age"`
}

type UpdateUserRequest struct {
	Authorization string `header:"authorization"`
	Name          string `path:"name"`
	Age           string `json:"age"`
}

type UpdateUserResponse struct {
	Message string `json:"message"`
}
