// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/vc/v1/create": {
            "post": {
                "description": "create vcluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "create"
                ],
                "summary": "create vcluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vcluster_gateway.Orders"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/create/workflow": {
            "post": {
                "description": "create vcluster from workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "create"
                ],
                "summary": "create vcluster from workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vcluster_gateway.Orders"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/delete": {
            "delete": {
                "description": "delete vcluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "delete"
                ],
                "summary": "Get VCluster Event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/edit/service": {
            "post": {
                "description": "Update VCluster Service info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "Update VCluster Service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "集群描述信息",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vcluster_gateway.VclusterInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.ProductSpec"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/event/": {
            "get": {
                "description": "get vcluster all event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Get VCluster Event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Event"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list": {
            "get": {
                "description": "get vcluster list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list"
                ],
                "summary": "get vcluster list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "enum": [
                            "1",
                            "0"
                        ],
                        "type": "string",
                        "default": "0",
                        "description": "集群状态，已删除(1)或正常运行(0)",
                        "name": "deleted",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.VCluster"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/configmaps": {
            "get": {
                "description": "get vcluster all configmap",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster configmap",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Configmap"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/deployments": {
            "get": {
                "description": "get vcluster all deployments",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster deploy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Deployment"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/events": {
            "get": {
                "description": "get vcluster all events",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.EventV1"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/ingress": {
            "get": {
                "description": "get vcluster all ingress",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster ingress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Ingress"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/namespaces": {
            "get": {
                "description": "get vcluster all namespace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster Namespace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Namespace"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/pods": {
            "get": {
                "description": "get vcluster all pods",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster pods",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Pod"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/pvc": {
            "get": {
                "description": "get vcluster all pvc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster pvc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Pvc"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/resourcequotas": {
            "get": {
                "description": "get vcluster all resourcequotas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource quota"
                ],
                "summary": "Get VCluster resourcequotas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Resourcequotas"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/secrets": {
            "get": {
                "description": "get vcluster all secret",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Secret"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/services": {
            "get": {
                "description": "get vcluster all service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.Service"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/list/statefulsets": {
            "get": {
                "description": "get vcluster all statefulsets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource list"
                ],
                "summary": "Get VCluster statefulset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.StatefulSet"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/pause": {
            "post": {
                "description": "pause vcluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pause"
                ],
                "summary": "pause VCluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "List of string ids",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/profiles": {
            "get": {
                "description": "get all profile info list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profiles"
                ],
                "summary": "List Profiles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.ProductSpec"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/resume": {
            "post": {
                "description": "resume vcluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resume"
                ],
                "summary": "resume VCluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "List of string ids",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vc/v1/token": {
            "get": {
                "description": "create VCluster token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "create VCluster token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 JWT token",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "集群id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.KubeConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.BaseResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "v1.Cluster": {
            "type": "object",
            "properties": {
                "insecure-skip-tls-verify": {
                    "type": "boolean"
                },
                "server": {
                    "type": "string"
                }
            }
        },
        "v1.Clusters": {
            "type": "object",
            "properties": {
                "cluster": {
                    "$ref": "#/definitions/v1.Cluster"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.Configmap": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "data": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "object": {}
            }
        },
        "v1.Configs": {
            "type": "object",
            "properties": {
                "configKey": {
                    "type": "string"
                },
                "configValue": {
                    "type": "string"
                }
            }
        },
        "v1.Context": {
            "type": "object",
            "properties": {
                "cluster": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "v1.Contexts": {
            "type": "object",
            "properties": {
                "context": {
                    "$ref": "#/definitions/v1.Context"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.Deployment": {
            "type": "object",
            "properties": {
                "avaliable": {
                    "type": "integer"
                },
                "containers": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "images": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "object": {},
                "ready": {
                    "type": "string"
                },
                "selector": {
                    "type": "string"
                },
                "updatedReplicas": {
                    "type": "integer"
                }
            }
        },
        "v1.Event": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "v1.EventV1": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "lastTime": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "object": {},
                "reason": {
                    "type": "string"
                }
            }
        },
        "v1.Ingress": {
            "type": "object",
            "properties": {
                "class": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "hosts": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "object": {}
            }
        },
        "v1.KubeConfig": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Clusters"
                    }
                },
                "contexts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Contexts"
                    }
                },
                "current-context": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "preferences": {
                    "$ref": "#/definitions/v1.Preferences"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Users"
                    }
                }
            }
        },
        "v1.Namespace": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "object": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "v1.Pod": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Event"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "node": {
                    "type": "string"
                },
                "object": {},
                "ready": {
                    "type": "string"
                },
                "restarts": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/v1.Status"
                }
            }
        },
        "v1.Preferences": {
            "type": "object"
        },
        "v1.ProductCategories": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "seq": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "v1.ProductSpec": {
            "type": "object",
            "properties": {
                "product_categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ProductCategories"
                    }
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Products"
                    }
                },
                "storage": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Storage"
                    }
                }
            }
        },
        "v1.Products": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "configs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Configs"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.Pvc": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "data": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "object": {}
            }
        },
        "v1.Resourcequotas": {
            "type": "object",
            "properties": {
                "cpu": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "gpu": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "memory": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "storage": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "v1.Secret": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "data": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "object": {},
                "type": {
                    "type": "string"
                }
            }
        },
        "v1.Service": {
            "type": "object",
            "properties": {
                "clusterIP": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "externalIPs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "object": {},
                "ports": {
                    "type": "string"
                },
                "selector": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1.StatefulSet": {
            "type": "object",
            "properties": {
                "containers": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "images": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "object": {},
                "ready": {
                    "type": "string"
                },
                "selector": {
                    "type": "string"
                }
            }
        },
        "v1.Status": {
            "type": "string",
            "enum": [
                "Running",
                "Starting",
                "Paused",
                "Deleted",
                "Unknown"
            ],
            "x-enum-varnames": [
                "StatusRunning",
                "StatusStarting",
                "StatusPaused",
                "StatusDeleted",
                "StatusUnknown"
            ]
        },
        "v1.Storage": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "integer"
                },
                "max": {
                    "type": "integer"
                },
                "min": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "storageClass": {
                    "type": "string"
                }
            }
        },
        "v1.User": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "v1.Users": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/v1.User"
                }
            }
        },
        "v1.VCluster": {
            "type": "object",
            "properties": {
                "apsURL": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "deleteTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instanceId": {
                    "type": "string"
                },
                "instanceSpec": {
                    "type": "string"
                },
                "manageBy": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "product": {
                    "type": "string"
                },
                "startedTime": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/v1.Status"
                },
                "utilizationRate": {
                    "description": "Storage         map[string]int ` + "`" + `gorm:\"-\" json:\"storage\"` + "`" + `",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.Resourcequotas"
                        }
                    ]
                }
            }
        },
        "vcluster_gateway.InstanceSpec": {
            "type": "object",
            "properties": {
                "paramName": {
                    "type": "string"
                },
                "paramValue": {
                    "type": "string"
                },
                "resourceSpecCode": {
                    "type": "string"
                },
                "resourceSpecId": {
                    "type": "integer"
                },
                "resourceSpecParamCode": {
                    "type": "string"
                },
                "resourceSpecParamId": {
                    "type": "integer"
                }
            }
        },
        "vcluster_gateway.OrderInfo": {
            "type": "object",
            "properties": {
                "actualAmount": {
                    "type": "integer"
                },
                "amount": {
                    "type": "integer"
                },
                "cycleCount": {
                    "type": "integer"
                },
                "orderType": {
                    "type": "integer"
                },
                "productCode": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                },
                "resourceTypeCode": {
                    "type": "string"
                },
                "resourceTypeId": {
                    "type": "integer"
                }
            }
        },
        "vcluster_gateway.Orderlist": {
            "type": "object",
            "properties": {
                "instanceId": {
                    "type": "string"
                },
                "instanceSpec": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vcluster_gateway.InstanceSpec"
                    }
                },
                "orderInfo": {
                    "$ref": "#/definitions/vcluster_gateway.OrderInfo"
                }
            }
        },
        "vcluster_gateway.Orders": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orderList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vcluster_gateway.Orderlist"
                    }
                },
                "tenantId": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "vclusterDesc": {
                    "type": "string"
                },
                "vclusterName": {
                    "type": "string"
                }
            }
        },
        "vcluster_gateway.VclusterInfo": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "context": {
                    "type": "string",
                    "example": "defaultcluster"
                },
                "desc": {
                    "type": "string"
                },
                "instanceId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orders": {
                    "$ref": "#/definitions/vcluster_gateway.Orders"
                },
                "product": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "GCP VclusterGateway Gateway API",
	Description:      "This is an authorization authentication proxy service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
